### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by judebert** [GiantCowFilms/Blend-Exchange#47]
I'm trying to attach my blend file to https://blender.stackexchange.com/questions/140347/glass-jelly-material-speckled-with-fireflies -- but I get a dialog that says "error uploading":

<img width="992" alt="Screen Shot 2019-05-11 at 1 17 35 PM" src="https://user-images.githubusercontent.com/2171690/57574510-33814a80-73ef-11e9-828b-1fb5e3ee0e24.png">

I'm using Chrome on OSX, with AdBlock and TamperMonkey disabled. The file name is "blx-jelly.blend", and I've tried it from several different directories.

**Comment by judebert** [comment]
Here's the .blend that won't upload.
[blx-jelly.zip](https://github.com/GiantCowFilms/Blend-Exchange/files/3169441/blx-jelly.zip)

**Comment by GiantCowFilms** [comment]
The Blend-Exchange, outage has been fixed. Thanks for letting me know about it.

The cause was that the credit card used to pay for the storage had expired, and I did not remember to update the payment settings with the new one.

In order to prevent this form happening again, I will do the following:

Pipe emails to Blend-Exchange to an email address that I actually read so I see billing error notices and other such issues.
